services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: barbs-container
    ports:
      - "8080:80"
    volumes:
      - ./:/app
    env_file:
      - .env
    restart: unless-stopped